EventManagementSystem_PPM/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('evento.urls'))
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

evento/urls.py
from django.urls import path
from . import views

app_name = 'evento'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('ListaEventi/', views.lista_eventi, name='lista_eventi'),
    path('DettagliEvento/<str:titolo>/', views.dettagli_evento, name='dettagli_evento'),
    path('Ricerca/', views.cerca_evento, name='cerca_evento'),
    path('Accesso/', views.accesso, name='accesso'),
    path('Registrazione/', views.registrazione, name='registrazione'),
    path('Esci/', views.esci, name='esci'),
    path('CreazioneEvento/', views.crea_evento, name='crea_evento'),
    path('ModificaEvento/<str:titolo>/', views.modifica_evento, name='modifica_evento'),
    path('Negazione/', views.negazione, name='negazione'),
    path('IscrizionePresente/', views.iscrizione_presente, name='iscrizione_presente'),
    path('PostiEsauriti/', views.posti_esauriti, name='posti_esauriti'),
    path('RimuoviEvento/<str:titolo>/', views.rimuovi_evento, name='rimuovi_evento'),
    path('Transazione/<str:titolo>/', views.compra_partecipazione, name='compra_partecipazione'),
    path('Pagato/', views.pagato, name='pagato'),
    path('Profilo/', views.info_profilo, name='info_profilo'),
    path('GestioneEventi/', views.gestione_eventi, name='gestione_eventi'),
    path('CreazioneCategoria/', views.crea_categoria, name='crea_categoria'),
    path('PagamentoInCorso/', views.transazione, name='transazione'),
    path('Rimborsato/', views.rimborso, name='rimborso'),
    path('Rimborso/<str:titolo>/', views.rimuovi_partecipazione, name='rimuovi_partecipazione'),
]

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="author" content="Francesca Sani">
    <meta name="description" content="Laboratorio 2 - PPM - Francesca Sani">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="keywords" content="Eventi">

    <title>{% block title %} Eventi {% endblock title %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <style>
        .carousel-inner .carousel-item img {
            width: 100%;
            height: 500px;
            object-fit: cover;
        }

        a{
            text-decoration: none;
        }

        .btn-outline-secondary:hover{
            color: white;
            background-color: darkcyan;
        }

        .btn-secondary:hover{
            color: white;
            background-color: darkcyan;
        }

        .btn-outline-secondary:hover{
            color: white;
            background-color: darkcyan;
        }

        .btn-outline-info:hover{
            color: white;
            background-color: darkcyan;
        }

        a:hover{
            color: white;
        }

    </style>

</head>

<body>
    <div>
        <nav class="navbar navbar-expand-lg" style="background-color: cadetblue">
            <div class="container-fluid">
                <form class="d-flex" role="search" method="GET" action="{% url 'evento:cerca_evento' %}">
                    <input class="form-control me-2" type="text" name="query" placeholder="Cerca..." aria-label="Cerca" value="{{ query }}" style="opacity: .3">
                    <button class="btn btn-outline-secondary" type="submit" style="border-color: white; color: white"> Cerca </button>
                </form>
                <a href="{% url 'evento:homepage' %}" class="navbar-brand" style="color: white"> Gestore Eventi </a>

                {% if user.is_authenticated %}
                    <div class="dropdown">
                        <button class="btn btn-outline-success me-2 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: white; opacity: 80%; color: cadetblue; border-color: cadetblue;">
                                <b> Benvenuto, {{ user.username }} </b>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'evento:info_profilo' %}"> Profilo </a>
                            <a class="dropdown-item" href="{% url 'evento:crea_evento' %}"> Crea Evento </a>
                            <a class="dropdown-item" href="{% url 'evento:gestione_eventi' %}"> Gestisci Eventi </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'evento:esci' %}"> Logout </a>
                        </div>
                    </div>
                {% else %}
                    <div>
                        <a href="{% url 'evento:accesso' %}">
                            <button class="btn btn-sm btn-outline-secondary" type="button" style="border-color: white; color: white"> Accedi </button>
                        </a>
                        <a href="{% url 'evento:registrazione' %}">
                            <button class="btn btn-outline-success me-2" type="button" style="background-color: white; opacity: 80%; color: cadetblue; border-color: cadetblue;">
                                <b> Registrati </b>
                            </button>
                        </a>
                    </div>
                {% endif %}
            </div>
        </nav>
    </div>

{% block content %}

{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>

    <script>
        $(document).ready(function() {
            $('.dropdown-toggle').click(function() {
                $('.dropdown-menu').toggle();
            });
        });
    </script>

</body>
</html>

templates/cerca_evento.html
{% extends 'base.html' %}

{% block title %} RICERCA {% endblock title %}

{% block content %}
    <p style="margin-top: 5px; margin-left: 25px">
        <a href="{% url 'evento:homepage' %}" class="link-dark"> HomePage </a>
    </p>
    <h1 style="color: darkcyan; margin-left: 25px"> Risultato ricerca: </h1>

    <ul>
        <div class="row blank">
            {% for evento in eventi %}

            <div class="col-xs-12 col-sm-6 col-md-5 col-lg-3 mt-3">
                <div class="card" style="width: 15rem;">
                    {% if evento.immagine %}
                    <img src="{{ MEDIA_URL }}{{ evento.immagine }}" class="card-img-top" alt="{{ evento.titolo }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ evento.titolo }}
                        </h5>
                        <p class="sub-title mb-2 text-body-secondary"> Data: {{ evento.data }} <br>
                            Orario: {{ evento.orario }}<br>
                            Luogo: {{ evento.luogo }}
                        </p>
                        <p class="card-text">
                            <small class="text-body-secondary"> Creato da: {{ evento.utente_creatore }} </small>
                        </p>
                        <a href="{% url 'evento:dettagli_evento' titolo=evento.titolo %}" class="btn btn-outline-secondary" style="border-color: darkcyan;"> Info </a>
                    </div>
                </div>
            </div>
            {% empty %}
                <div class="d-flex justify-content-center mt-3">
                    <div class="card col-11" style="background-color: lightgrey;">
                        <div class="row g-0">
                            <div class="card-body" style="text-align: center">
                                <h2 class="card-title" style="color: darkcyan">
                                    Nessun risultato trovato in seguito alla tua ricerca!
                                </h2>
                                <p style="padding-top: 3px">
                                    <a href="{% url 'evento:lista_eventi' %}" class="link-dark"> Visualizza Lista Eventi </a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </ul>

{% endblock %}

templates/crea_categoria.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %} CREAZIONE CATEGORIA {% endblock title %}

{% block content %}

    <p style="margin-top: 5px; margin-left: 25px">
        <a href="{% url 'evento:homepage' %}" class="link-dark"> HomePage </a>
    </p>
    <div class="m-4">
        <h1 style="color: darkcyan;"> Crea la categoria </h1>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}

            <button class="btn btn-outline-secondary ml-2" type="submit" style="border-color: darkcyan;">
                Crea
            </button>
            <button class="btn btn-outline-secondary ml-2" type="reset" style="border-color: darkcyan;">
                Cancella
            </button>
        </form>
    </div>

{% endblock %}

templates/crea_evento.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %} CREAZIONE EVENTO {% endblock title %}

{% block content %}

    <p style="margin-top: 5px; margin-left: 25px">
        <a href="{% url 'evento:homepage' %}" class="link-dark"> HomePage </a>
    </p>
    <div class="m-4">
        <h1 style="color: darkcyan;"> Crea il tuo evento </h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <div class="m-2" style="background-color: cadetblue; opacity: 85%">
            <p class="m-4 p-2">
                Se la categoria di appartenenza dell'evento non è presente aggiugnila
                <a href="{% url 'evento:crea_categoria' %}"> Crea </a> <br>
                <b>IMPORTANTE:</b> Il valore 100000000 nel campo capienza massima indica che non si ha capienza massima. <br>
            </p>
                </div>

            <button class="btn btn-outline-secondary ml-2" type="submit" style="border-color: darkcyan;">
                Crea
            </button>
            <button class="btn btn-outline-secondary ml-2" type="reset" style="border-color: darkcyan;">
                Cancella
            </button>
        </form>
    </div>

{% endblock %}

templates/dettagli_evento.html
{% extends 'base.html' %}

{% block title %} LISTA EVENTI {% endblock title %}

{% block content %}
    <p style="margin-top: 5px; margin-left: 25px">
        <a href="{% url 'evento:homepage' %}" class="link-dark"> HomePage </a>
    </p>
    <h1 style="color: darkcyan; text-align: center; margin-top: 5px"> Dettagli Evento </h1>
<div class="d-flex justify-content-center mt-3">
    <div class="card col-11" style="background-color: lightgrey;">
        <div class="row g-0">
            <div class="col-md-6">
                {% if evento.immagine %}
                <img src="{{ MEDIA_URL }}{{ evento.immagine }}" class="card-img-top" alt="{{ evento.titolo }}">
                {% endif %}
            </div>
            <div class="col-md-6">
                <div class="card-body" style="text-align: center">
                    <h2 class="card-title" style="color: darkcyan"> {{ evento.titolo }} </h2>
                    <p class="card-text"> {{ evento.descrizione }} </p>
                    <p class="card-text">
                        <strong> Info evento: </strong> <br>
                        <i> Data: </i> {{ evento.data }} <br>
                        <i> Orario: </i> {{ evento.orario }} <br>
                        <i> Luogo: </i> {{ evento.luogo }} <br>
                        <i> Capienza massima: </i> {{ evento.capienza_massima }} <br>
                        <i> Posti disponibili: </i> {{ evento.posti_disponibili }} <br>
                        <i> Programma: </i> <br> {{ evento.programma }}
                    </p>
                    <p class="card-text">
                        <small class="text-body-secondary"> Creato da - {{ evento.utente_creatore }} </small>
                    </p>
                    {% if user.is_authenticated %}
                        <a href="{% url 'evento:compra_partecipazione' titolo=evento.titolo %}" class="btn btn-outline-secondary" style="border-color: darkcyan;"> Acquista </a>
                        <!--<a href="{#% url 'evento:rimuovi_partecipazione' titolo=evento.titolo %#}" class="btn btn-outline-secondary" style="border-color: darkcyan;"> Rimborso </a>-->
                    {% else %}
                        <a href="{% url 'evento:accesso' %}" class="btn btn-outline-secondary" style="border-color: darkcyan;"> Accedi </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/gestione_eventi.html
{% extends 'base.html' %}

{% block title %} GESTIONE EVENTI {% endblock title %}

{% block content %}
    <p style="margin-top: 5px; margin-left: 25px">
        <a href="{% url 'evento:homepage' %}" class="link-dark"> HomePage </a>
    </p>
    <h1 style="color: darkcyan; text-align: center; margin-top: 5px"> Gestione degli eventi creati  </h1>

    <ul>
        <div class="row blank">
            {% for evento in eventi %}
                <div class="col-xs-12 col-sm-6 col-md-5 col-lg-3 mt-3">
                    <div class="card" style="width: 15rem;">
                        {% if evento.immagine %}
                        <img src="{{ MEDIA_URL }}{{ evento.immagine }}" class="card-img-top" alt="{{ evento.titolo }}">
                        {% endif %}
                        <div class="card-body">
                        <h5 class="card-title">
                            {{ evento.titolo }}
                        </h5>
                        <p class="sub-title mb-2 text-body-secondary"> Data: {{ evento.data }} <br>
                            Orario: {{ evento.orario }}<br>
                            Luogo: {{ evento.luogo }}
                        </p>
                        <a href="{% url 'evento:modifica_evento' titolo=evento.titolo %}" class="btn btn-outline-secondary" style="border-color: darkcyan"> Modifica </a>
                        <a href="{% url 'evento:rimuovi_evento' titolo=evento.titolo %}" class="btn btn-outline-secondary" style="border-color: darkcyan"> Rimuovi </a>
                    </div>
                </div>
            </div>
            {% empty %}
                <div class="d-flex justify-content-center mt-3">
                    <div class="card col-11" style="background-color: lightgrey;">
                        <div class="row g-0">
                            <div class="card-body" style="text-align: center">
                                <h2 class="card-title" style="color: darkcyan">
                                    Non sono stati creati eventi
                                </h2>
                                <a href="{%  url 'evento:crea_evento' %}" class="link-dark" > Crea un evento </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </ul>


{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>
        Hello word!
    </h2>
</body>
</html>

templates/info_profilo.html
{% extends 'base.html' %}

{% block title %} PROFILO PERSONALE {% endblock title %}

{% block content %}
    <p style="margin-top: 5px; margin-left: 25px">
        <a href="{% url 'evento:homepage' %}" class="link-dark"> HomePage </a>
    </p>
    <h1 style="color: darkcyan; text-align: center; margin-top: 5px"> {{ user.username }} benvenuto/a nel tuo profilo  </h1>
    <h4 style="color: darkcyan; margin-top: 5px; margin-left: 25px"> Lista eventi acquistati:  </h4>
    <ul>
        <div class="row blank">
            {% for evento in iscritti_evento %}
                <div class="col-xs-12 col-sm-6 col-md-5 col-lg-3 mt-3">
                    <div class="card" style="width: 15rem;">
                        {% if evento.immagine %}
                         <img src="{{ MEDIA_URL }}{{ evento.immagine }}" class="card-img-top" alt="{{ evento.titolo }}">
                        {% endif %}
                        <div class="card-body">
                        <h5 class="card-title">
                            {{ evento.titolo }}
                        </h5>
                        <p class="sub-title mb-2 text-body-secondary"> Data: {{ evento.data }} <br>
                            Orario: {{ evento.orario }}<br>
                            Luogo: {{ evento.luogo }}
                        </p>
                        <p class="card-text">
                            <small class="text-body-secondary"> Creato da: {{ evento.utente_creatore }} </small>
                        </p>
                        <a href="{% url 'evento:dettagli_evento' titolo=evento.titolo %}" class="btn btn-outline-secondary" style="border-color: darkcyan"> Info </a>
                        <a href="{% url 'evento:rimuovi_partecipazione' titolo=evento.titolo %}" class="btn btn-outline-secondary" style="border-color: darkcyan;"> Rimborso </a>
                    </div>
                </div>
            </div>
            {% empty %}
                <div class="d-flex justify-content-center mt-3">
                    <div class="card col-11" style="background-color: lightgrey;">
                        <div class="row g-0">
                            <div class="card-body" style="text-align: center">
                                <h2 class="card-title" style="color: darkcyan">
                                    Al momento non sei iscritto a nessun evento
                                </h2>
                                <a href="{%  url 'evento:lista_eventi' %}" class="link-dark" > Visualizza gli eventi in programma </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </ul>


{% endblock %}

templates/iscrizione_presente.html
{% extends 'base.html' %}

{% block title %} ISCRIZIONE PRESENTE  {% endblock title %}

{% block content %}
    <h1 style="color: red; text-align: center; margin-top: 5px">
        <b> ERRORE: </b>
    </h1>
    <div class="d-flex justify-content-center mt-3">
        <div class="card col-11" style="background-color: lightgrey;">
            <div class="row g-0">
                <div class="card-body" style="text-align: center">
                    <h2 class="card-title" style="color: darkcyan">
                        Hai già acquistato il biglietto e sei già iscritto all'evento!
                    </h2>
                    <p style="padding-top: 3px">
                        <a href="{% url 'evento:info_profilo' %}" class="link-dark"> Visualizza Profilo </a>
                    </p>
                    <p>
                        <a href="{% url 'evento:homepage' %}" class="link-dark"> Torna alla HomePage </a>
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/pagato.html
{% extends 'base.html' %}

{% block title %} PAGAMENTO EFFETTUATO {% endblock title %}

{% block content %}
    <h1 style="color: red; text-align: center; margin-top: 5px">
        <b> Attenzione </b>
    </h1>
    <div class="d-flex justify-content-center mt-3">
        <div class="card col-11" style="background-color: lightgrey;">
            <div class="row g-0">
                <div class="card-body" style="text-align: center">
                    <h2 class="card-title" style="color: darkcyan">
                        Pagamento effettuato
                    </h2>
                    <p style="margin-top: 5px">
                        <a href="{% url 'evento:homepage' %}" class="link-dark"> Torna alla HomePage </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/posti_esauriti.html
{% extends 'base.html' %}

{% block title %} POSTI ESAURITI  {% endblock title %}

{% block content %}
    <h1 style="color: red; text-align: center; margin-top: 5px">
        <b> ERRORE: </b>
    </h1>
    <div class="d-flex justify-content-center mt-3">
        <div class="card col-11" style="background-color: lightgrey;">
            <div class="row g-0">
                <div class="card-body" style="text-align: center">
                    <h2 class="card-title" style="color: darkcyan">
                        Siamo spiacenti, ma è stata raggiunta la capienza massima per questo evento!
                    </h2>
                    <p style="margin-top: 5px">
                        <a href="{% url 'evento:homepage' %}" class="link-dark"> Torna alla HomePage </a>
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/rimborso.html
{% extends 'base.html' %}

{% block title %} RIMBORSO EFFETTUATO {% endblock title %}

{% block content %}
    <h1 style="color: red; text-align: center; margin-top: 5px">
        <b> Attenzione </b>
    </h1>
    <div class="d-flex justify-content-center mt-3">
        <div class="card col-11" style="background-color: lightgrey;">
            <div class="row g-0">
                <div class="card-body" style="text-align: center">
                    <h2 class="card-title" style="color: darkcyan">
                        Rimborso effettuato
                    </h2>
                    <p style="margin-top: 5px">
                        <a href="{% url 'evento:homepage' %}" class="link-dark"> Torna alla HomePage </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/rimuovi_evento.html
{% extends 'base.html' %}

{% block title %} EVENTO RIMOSSO {% endblock title %}

{% block content %}
    <div class="d-flex justify-content-center mt-3">
        <div class="card col-11" style="background-color: lightgrey;">
            <div class="row g-0">
                <div class="card-body" style="text-align: center">
                    <h2 class="card-title" style="color: darkcyan">
                        Evento selezionato rimosso con successo!
                    </h2>
                    <p style="margin-top: 5px">
                        <a href="{% url 'evento:homepage' %}" class="link-dark"> Torna alla HomePage </a>
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/transazione.html
{% extends 'base.html' %}

{% block title %} PAGAMENTO IN CORSO {% endblock title %}

{% block content %}
    <h1 style="color: red; text-align: center; margin-top: 5px">
        <b> Pagamento in corso... </b>
    </h1>
    <div class="d-flex justify-content-center mt-3">
    <a href="{% url 'evento:pagato' %}">
        <button class="btn btn-outline-secondary ml-2" type="submit" style="border-color: darkcyan">
                Autorizza pagamento
        </button>
    </a>
    </div>
{% endblock %}